<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-J9JQ713" failures="1" tests="2" name="script.TC_001" time="75.763" errors="0" timestamp="2023-03-28T17:30:38 IST" skipped="1">
  <testcase classname="script.TC_001" name="verifyAddedCustomerShowsInUSPDropDown" time="13.710">
    <failure message="expected [BangaloretW lifeic] but found [BangaloretW lifeicNfs]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [BangaloretW lifeic] but found [BangaloretW lifeicNfs]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at script.TC_001.verifyAddedCustomerShowsInUSPDropDown(TC_001.java:69)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- verifyAddedCustomerShowsInUSPDropDown -->
  <system-out/>
  <testcase classname="script.TC_001" name="verifyAddedCustomerShowsInUSPDropDown" time="62.053">
    <skipped/>
  </testcase> <!-- verifyAddedCustomerShowsInUSPDropDown -->
  <system-out/>
</testsuite> <!-- script.TC_001 -->
